[project]
name = "demand-forecast"
requires-python = ">=3.9"
version = "2025.0.0"
dependencies = [
    "pandas",
    "numpy",
    "json",
    "joblib",
    "pydantic_settings",
    "openpyxl",
    "scikit-learn",
    "pyswarms",
    "lightgbm",

]
